/****** Script for SelectTopNRows command from SSMS  ******/
SELECT [TrafficType]
      ,[TrafficCategory]
      ,[TrafficSubcategory]
      ,[TrafficDivision]
      ,[TrafficChannel]
      ,[IsPaidTraffic]
      ,[CampaignTargetCategoryId]
      ,[CampaignTargetWebLevel1]
      ,[CampaignTargetWebLevel2]
      ,[CampaignTargetWebLevel3]
      ,[CampaignTargetWebLevel4]
      ,[CampaignTargetWebLevel5]
      ,[CampaignTargetWebLevel6]
  FROM [MDWH_RAW].[raw_gbq168810_g161014_dwh_output].[dimUtm]
  
  [core].[utm_gbq]
  [core].[utm]
  [core].[utm_sync]