		null as [#collection_id#],
		null as [#collection_type_id#],
		null as [#parent_id#],
		null as [#identifier#],
		null as [#parent_identifier#],
		null as [#collection_name#],
		null as [#collection_display_name#],
		null as [#is_active#],